name: Validate Global Policy Explorer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Simulate treaty queries with GraphRAG + NLWeb
      run: |
        python - <<EOF
        import json
        from graphrag.query_graph import query_graph
        from nlweb.app import enrich_response
        from weaviate_setup.ingest import get_client

        # Load sample queries
        with open("data/sample_treaties.json", "r") as f:
            queries = json.load(f)

        # Initialize Weaviate client
        client = get_client()

        for i, item in enumerate(queries, 1):
            query = item["query"]
            print(f"--- Query {i} ---")
            print(f"User query: {query}")

            try:
                graph_output = query_graph(query, client)
                enriched_output = enrich_response(query)
                print(f"GraphRAG output: {graph_output}")
                print(f"NLWeb enrichment: {enriched_output}\n")
            except Exception as e:
                print(f"Error: {e}\n")
        EOF
