name: Validate Global Policy Explorer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install matplotlib networkx python-dotenv

    - name: Simulate multiple user queries
      run: |
        echo "queries = [" > demo.py
        echo "  ('What is the Paris Agreement?', 'France agrees to reduce carbon emissions by 40% by 2030.')," >> demo.py
        echo "  ('What does the Kyoto Protocol require?', 'Japan commits to reducing greenhouse gas emissions by 6% below 1990 levels.')," >> demo.py
        echo "  ('What is the Montreal Protocol?', 'Countries agree to phase out ozone-depleting substances like CFCs.')," >> demo.py
        echo "  ('What is the role of the IPCC?', 'The IPCC provides scientific assessments on climate change to inform policy decisions.')," >> demo.py
        echo "  ('What is COP26?', 'COP26 focused on accelerating action toward the goals of the Paris Agreement.')," >> demo.py
        echo "  ('What is the Green Climate Fund?', 'It helps developing countries finance climate mitigation and adaptation efforts.')" >> demo.py
        echo "]" >> demo.py
        echo "for i, (query, response) in enumerate(queries, 1):" >> demo.py
        echo "    print(f'--- Query {i} ---')" >> demo.py
        echo "    print(f'User query: {query}')" >> demo.py
        echo "    print(f'Response: {response}\\n')" >> demo.py
        python demo.py

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Visualize GraphRAG knowledge graph
      run: python graphrag/visualize.py

    - name: Upload GraphRAG visualization
      uses: actions/upload-artifact@v3
      with:
        name: graphrag-visual
        path: graphrag/graphrag_visual.png

