name: Validate Global Policy Explorer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Simulate queries using project modules
      run: |
        echo "from graphrag.core import GraphRAG" > demo.py
        echo "from nlweb.interface import NLWebInterface" >> demo.py
        echo "from weaviate_setup.client import get_client" >> demo.py
        echo "" >> demo.py
        echo "# Initialize components" >> demo.py
        echo "client = get_client()" >> demo.py
        echo "graphrag = GraphRAG(client)" >> demo.py
        echo "nlweb = NLWebInterface()" >> demo.py
        echo "" >> demo.py
        echo "queries = [" >> demo.py
        echo "  'What is the Paris Agreement?', " >> demo.py
        echo "  'What does the Kyoto Protocol require?', " >> demo.py
        echo "  'What is the Montreal Protocol?', " >> demo.py
        echo "  'What is the role of the IPCC?', " >> demo.py
        echo "  'What is COP26?', " >> demo.py
        echo "  'What is the Green Climate Fund?'" >> demo.py
        echo "]" >> demo.py
        echo "" >> demo.py
        echo "for i, query in enumerate(queries, 1):" >> demo.py
        echo "    print(f'--- Query {i} ---')" >> demo.py
        echo "    print(f'User query: {query}')" >> demo.py
        echo "    print(f'GraphRAG response: {graphrag.answer(query)}')" >> demo.py
        echo "    print(f'NLWeb enrichment: {nlweb.enrich_response(query)}\\n')" >> demo.py
        python demo.py

