name: Validate Global Policy Explorer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Simulate user query
      run: |
        echo "query = 'What is the Paris Agreement?'" > demo.py
        echo "clause = 'France agrees to reduce carbon emissions by 40% by 2030.'" >> demo.py
        echo "print(f'User query: {query}')" >> demo.py
        echo "print(f'Response: {clause}')" >> demo.py
        python demo.py
